description: MMP 350 class website
class: MMP 350
semester: s18
baseurl: /mmp350
layouts_dir: slides/_jeks/layouts
includes_dir: slides/_jeks/includes
exclude:
  - README.md
  - update.sh
  - test/
  - examples/